#!/bin/sh
#-----------------------------------------------------------------------
# Create and install the lensmon programs and their libraries.
#-----------------------------------------------------------------------

echo ' '; echo 'Compiling the local nr library liblocnr.a'; echo ' '
(cd locnr; make)

echo ' '; echo 'Compiling a subset of the slalib library libslalib.a'; echo ' '
(cd $SLADIR; make)

echo ' '; echo 'Compiling the scratch file utils library libscrfil.a'; echo ' '
(cd $FITSFNDIR/MCSfits/scrfil_src; make)

echo ' '; echo 'Compiling the log I/O library liblogio.a'; echo ' '
(cd $FITSFNDIR/MCSfits/logio_src; make)

echo ' '; echo 'Compiling the record I/O interface library librecio.a'; echo ' '
(cd $FITSFNDIR/MCSfits/recio_src; make)

echo ' '; echo 'Compiling the fits library libfits.a'; echo ' '
(cd $FITSFNDIR/MCSfits/fits_src; make)

echo ' '; echo 'Compiling the general utility library libutil.a'; echo ' '
(cd $CDFUTIL; make)

echo ' '; echo 'Compiling the light-curve library liblcfn.a'
echo ' and the programs themselves'; echo ' '
(cd main_src; make)

