/*
 * modscal.c
 *
 * Program to scale clean component models for use with difmap.
 *
 * Usage: modscal source_name [input_file]
 *
 * 16Dec96 CDF
 * v17Dec96 CDF, Now create a script file to run in difmap based on root
 *                source name.
 * v03Jan97 CDF, Added a wtscal paramter for more reasonable chi-squared
 *                values.
 *               Corrected printing of scale factor
 * v04Jan97 CDF, Now calculates the total flux in the clean components and
 *                prints out scaled total flux rather than just the
 *                scale.
 * v05Jan97 CDF, Outputs model number as well as scaled flux
 * v07Jan97 CDF, Corrected header output.
 *               Outputs scale in addition to model number and scaled flux
 *               Phasecal time determined by source
 *               *Change output to be a shell script file that runs the
 *                difmap script file that is also generated by the program*
 * v14Jan97 CDF, Got rid of the generation of the difmap script to view
 *                the results of the modelfitting.
 *               Changed path names.
 * v15Jan97 CDF, Added the image rms to output from difmap script
 *               Changed the shell script to call an awk script rather than
 *                the C program modfit_dat.c
 * v16Jan97 CDF, Removed the shell script generating section of the program
 * v06Mar97 CDF, Allowed input models with gaussian (as opposed to point)
 *                components.
 * v19Mar97 CDF, Changed root.X.UVF to root_edt.uvf
 * v20Mar97 CDF, Allowed for different input models and batch-mode execution
 *               Took out functions and put them into modfuncs.c
 * v30Mar97 CDF, Gets MJD from FITS header info
 * v02Apr97 CDF, Puts in 1635 shift only before 21 Mar 97 obsdate.
 * v17Apr97 CDF, Read in corrected 1635 model after 21Mar97 obsdate
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "modfuncs.h"

/*.......................................................................
 *
 * Function declarations
 *
 */


/*.......................................................................
 *
 * Main Program
 *
 */

int main(int argc, char *argv[])
{
  int no_error=1;         /* Flag set to 0 on error */
  int infile_exists=0;    /* Flag set to 1 if input file exists */
  int interact=1;         /* Set to 0 in batch-mode */
  float smin,smax,sstep;  /* Scaling parameters */
  float caltime;          /* Phase selfcal timescale (for 1608) */
  float obsdate;          /* MJD of observation */
  char line[MMAX];         /* General string for reading input */
  char infile[MMAX];       /* Optional input file name */
  char *root;             /* Source root name */
  char ext[MMAX];          /* Extension for file names */
  char modname[MMAX];      /* Input model filename */
  Compinfo *cinfo=NULL;   /* Component information */
  FILE *mfp=NULL;         /* Pointer to model input file */
  FILE *ifp=NULL;         /* Pointer to optional input file */
  
  

  /*
   * Check command line
   */

  if(argc < 2 || argc > 3) {
    fprintf(stderr,"\nUsage: modscal source_root-name [input_file]\n");
    fprintf(stderr," where the source root name is, for example, 1635\n");
    fprintf(stderr," in the case where the model file is 1635.mod and the\n");
    fprintf(stderr," source UVF data file is 1635_edt.uvf\n");
    fprintf(stderr,"\nIf the optional input file exists, it will contain\n");
    fprintf(stderr," information to be used in the model scaling\n\n");
    return 1;
  }

  /*
   * First get the source root name
   */
 
  root = argv[1];

  /*
   * Now get the extension and set up caltime defaults
   */

  if(argc == 2) {
    get_ext(ext);
    default_caltimes(root,&caltime);
  }

  /*
   * or open the input file, which contains the extension as well as the
   * scale factor information
   */

  else {
    strcpy(infile,argv[2]);
    while((ifp = fopen(infile,"r")) == NULL) {
      fprintf(stderr,"ERROR. %s does not exist.  Enter new filename:  ",
	      infile);
      gets(infile);
    }
    infile_exists = 1;
  }

  /*
   * If the input file exists, get info from it
   */

  if(infile_exists) {
    if(read_in_params(ifp,root,ext,&smin,&smax,&sstep,&caltime,&interact))
      no_error = 0;
  }
    
  /*
   * Make sure that the associated UVF file exists, and get MJD obsdate
   *  from it.
   */

  if(check_uvf(root,ext,&obsdate)) {
    if(strcmp(root,"1635") == 0) {
      fprintf(stderr,"*****************************\n");
      fprintf(stderr,"ERROR: No UVF file found -- assuming pre-21Mar97");
      fprintf(stderr,"models\n");
      fprintf(stderr,"*****************************\n\n\n");
      obsdate = 0;
    }
  }

  get_modname(modname,root,ext,obsdate);

  /*
   * If the source is 1608, it needs to be treated in a manner different
   *  from that associated with the sources 1634 and 1635.  Check the
   *  source root name and act accordingly
   */

  if(no_error && strcmp(root,"1608") == 0) {
    if(argc == 2) {
      printf("\nEnter 1608 phase selfcal timescale: [%4.1f]",caltime);
      gets(line);
      if(strcmp(line,"") != 0)
	if(sscanf(line,"%f",&caltime) != 1)
	  no_error = 0;
    }
    if(no_error)
      if(modfile_08(root,ext,caltime,interact))
	no_error = 0;
  }

  /*
   * Dealing with comparison sources
   */

  else if(no_error) {

    /*
     * Check to see that the model file can be opened.
     */

    
    if((mfp = open_modfile(modname)) == NULL)
      no_error = 0;

    /*
     * Get minimum and maximum scale and step size if not set by input file
     */

    if(no_error)
      if(argc == 2)
	if(get_sinfo(&smin,&smax,&sstep))
	  no_error = 0;

    /*
     * Scale the model by the scaling factors
     */

    if(no_error)
      if(scale_data(root,ext,smin,smax,sstep,caltime,interact,mfp))
	no_error = 0;
  }

  /*
   * Free up the memory
   */

  cinfo = del_cinfo(cinfo);

  /*
   * Close the input file(s)
   */

  if(mfp)
    fclose(mfp);

  if(ifp)
    fclose(ifp);
  
  if(no_error)
    return 0;
  else {
    fprintf(stderr,"\nERROR. Exiting program\n\n");
    return 1;
  }
}
