/*
 * modscal.c
 *
 * Program to scale clean component models for use with difmap.
 *
 * Usage: modscal source_name [input_file]
 *
 * 16Dec96 CDF
 * v17Dec96 CDF, Now create a script file to run in difmap based on root
 *                source name.
 * v03Jan97 CDF, Added a wtscal paramter for more reasonable chi-squared
 *                values.
 *               Corrected printing of scale factor
 * v04Jan97 CDF, Now calculates the total flux in the clean components and
 *                prints out scaled total flux rather than just the
 *                scale.
 * v05Jan97 CDF, Outputs model number as well as scaled flux
 * v07Jan97 CDF, Corrected header output.
 *               Outputs scale in addition to model number and scaled flux
 *               Phasecal time determined by source
 *               *Change output to be a shell script file that runs the
 *                difmap script file that is also generated by the program*
 * v14Jan97 CDF, Got rid of the generation of the difmap script to view
 *                the results of the modelfitting.
 *               Changed path names.
 * v15Jan97 CDF, Added the image rms to output from difmap script
 *               Changed the shell script to call an awk script rather than
 *                the C program modfit_dat.c
 * v16Jan97 CDF, Removed the shell script generating section of the program
 * v06Mar97 CDF, Allowed input models with gaussian (as opposed to point)
 *                components.
 * v19Mar97 CDF, Changed root.X.UVF to root_edt.uvf
 * v20Mar97 CDF, Allowed for different input models and batch-mode execution
 *               Took out functions and put them into modfuncs.c
 * v30Mar97 CDF, Gets MJD from FITS header info
 * v02Apr97 CDF, Puts in 1635 shift only before 21 Mar 97 obsdate.
 * v17Apr97 CDF, Read in corrected 1635 model after 21Mar97 obsdate
 * v04May01 CDF, Complete change, to just producing scaled model from an
 *                input model.  Let the rest of the former functionality
 *                be taken by flexible difmap and shell scripts.
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "dataio.h"
#include "modfuncs.h"

/*.......................................................................
 *
 * Main Program
 *
 */

int main(int argc, char *argv[])
{
  int no_error=1;         /* Flag set to 0 on error */
  int interact=1;         /* Set to 0 in batch-mode */
  float smin,smax,sstep;  /* Scaling parameters */
  float caltime;          /* Phase selfcal timescale (for 1608) */
  float obsdate;          /* MJD of observation */
  char line[MMAX];        /* General string for reading input */
  char infile[MMAX];      /* Optional input file name */
  char *root;             /* Source root name */
  char ext[MMAX];         /* Extension for file names */
  char modname[MMAX];     /* Input model filename */
  FILE *mfp=NULL;         /* Pointer to model input file */
  FILE *ifp=NULL;         /* Pointer to optional input file */
  
  /*
   * Check command line
   */

  if(argc < 2 || argc > 3) {
    fprintf(stderr,"\nUsage: modscal input_model_name [setup_file]\n");
    fprintf(stderr,"\nIf the optional input file exists, it will contain\n");
    fprintf(stderr," information to be used in the model scaling\n\n");
    return 1;
  }

  /*
   * Get the model file name
   */
 
  strcpy(modname,argv[1]);

  /*
   * Open the setup file, which contains the scale factor information
   */
#if 0
  if(argc == 3) {
    strcpy(infile,argv[2]);
    if(!(ifp = open_readfile(infile))) 
      no_error = 0;
    else {
      if(read_in_params(ifp,root,ext,&smin,&smax,&sstep,&caltime,&interact))
	no_error = 0;
    }
  }
#endif    
  /*
   * Scale the model.
   */

  if(no_error) {

    /*
     * Get minimum and maximum scale and step size if not set by input file
     */

    if(no_error && argc == 2)
      if(get_sinfo(&smin,&smax,&sstep))
	no_error = 0;

    /*
     * Scale the model by the scaling factors
     */

    if(no_error)
      if(scale_data(smin,smax,sstep,modname))
	no_error = 0;
  }

  /*
   * Close the input file(s)
   */

  if(mfp)
    fclose(mfp);

  if(ifp)
    fclose(ifp);
  
  if(no_error)
    return 0;
  else {
    fprintf(stderr,"\nERROR. Exiting program\n\n");
    return 1;
  }
}
