/*
 * plot_chisq.c
 *
 * Reads in files containing a list of chisq values calculated at points
 *  on a two dimensional grid.  Makes a contour plot of the results.  The
 *  input file is generated by the lcurve.c program.
 *
 * Usage: plot_chisq [input file]
 *
 * 10Jun98 CDF
 * v24Jul98 CDF, Wider lines for plotting.
 * v04Aug98 CDF, Changed max y value for plot_curve to be 1.05 * ymax
 * v31Jan99 CDF, Modified contour levels in plot_contours to match the
 *                68.3, 90, 95.4, and 99% confidence intervals for ONE of
 *                the fitted parameters when projected onto the relevant
 *                axis.
 *               Modified to read in chisq as well as reduced chisq from
 *                the input file.  This allows the correct confidence
 *                contours to be plotted in plot_contours.
 * v08Sep00 CDF, More graceful transition between plots.
 *               Started transition to the new LCchisq structure.  This
 *                involved transferring the data-reading functionality to
 *                the new read_lcchisq function in lc_chisq.c.
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "structdef.h"
#include "dataio.h"
#include "plotfuncs.h"
#include "cpgplot.h"
#include "lc_chisq.h"

#define NCONT 4  /* Number of contour levels */
#define DCHI 1.0 /*Step size for chisq contours */

/*.......................................................................
 *
 * Function declarations
 *
 */

int plot_contours(float *chisq, int nx, int ny, float centx, float centy,
		  float centxval, float centyval, float chimin);
int minmax(float *array, int size, float *min, float *max, int *minpos, 
	   int *maxpos, char *arrname, int verbose);
int onedslice(float *x, float *y, float *chisq, int nx, int ny, int minpos);
int plot_curve(float *cx, float *cy, int size, float ymax, char *xlab);

/*.......................................................................
 *
 * Main program
 *
 */

int main(int argc, char *argv[])
{
  int i;                 /* Looping variable */
  int no_error=1;        /* Flag set to 0 on error */
  int nx,ny;             /* Dimensions of input array */
  int minpos,maxpos;     /* Positions of min and max array values */
  int xpos,ypos;         /* The fortran x and y positions of chimin */
  float xmin,xmax;       /* Min and max values in x array */
  float ymin,ymax;       /* Min and max values in y array */
  float rchimin,rchimax; /* Min and max values in rchisq array */
  float *x=NULL;         /* x coordinate of the grid */
  float *y=NULL;         /* y coordinate of the grid */
  float *chisq=NULL;     /* Array of chisq values */
  float *rchisq=NULL;    /* Array of reduced chisq values */
  float *xptr,*yptr;     /* Pointers for navigating x and y arrays */
  float *chiptr;         /* Pointer for navigating chisq array */
  float *rchiptr;        /* Pointer for navigating rchisq array */
  float cheight=1.2;     /* Character height for plot axis labels */
  char inname[MAXC];     /* Name of the input file */
  Axisinfo tau,mu;       /* Axis information for delay and magnif. axes */
  LCchisq *lcchisq;      /* Container for grid information */
  LCchisq *lcptr;        /* Pointer to navigate lcchisq */

  /*
   * Check input
   */

  if(argc != 2) {
    fprintf(stderr,"\nUsage: plot_chisq [input file]\n\n");
    return 1;
  }

  /*
   * Read data from input file
   */

  strcpy(inname,argv[1]);
  if(!(lcchisq = read_lcchisq(inname,&tau,&mu))) {
    fprintf(stderr,"ERROR: Exiting plot_chisq.\n");
    return 1;
  }

  /*
   * Transfer data from Axisinfo structures to old x and y structures.
   */

  nx = tau.nval;
  ny = mu.nval;
  xmin = tau.minval;
  xmax = tau.maxval;
  ymin = mu.minval;
  ymax = mu.maxval;

  /*
   * Allocate memory for arrays
   */

  if(!(x = new_array(nx*ny,1)))
    no_error = 0;

  if(!(y = new_array(nx*ny,1)))
    no_error = 0;

  if(!(chisq = new_array(nx*ny,1)))
    no_error = 0;

  if(!(rchisq = new_array(nx*ny,1)))
    no_error = 0;

  /*
   * Transfer data from LCchisq structure into one-dimensional arrays
   */

  if(no_error) {
    for(i=0,xptr=x,yptr=y,chiptr=chisq,rchiptr=rchisq,lcptr=lcchisq; i<nx*ny;
	i++,xptr++,yptr++,chiptr++,rchiptr++,lcptr++) {
      *xptr = lcptr->tau;
      *yptr = lcptr->mu;
      *chiptr = lcptr->chisq;
      *rchiptr = lcptr->rchisq;
    }
  }

  /*
   * Get min and max values
   */

  if(no_error) {
    if(minmax(rchisq,nx*ny,&rchimin,&rchimax,&minpos,&maxpos,"red. chisq",0))
      no_error = 0;
    else {
      printf("\nMin reduced chisq of %f (chisq = %f) at grid point:\n",
	     rchimin,chisq[minpos]);
      printf(" (%7.2f, %f) [(%7.2f, %f)]\n\n",
	     x[minpos],y[minpos],x[minpos],1.0/y[minpos]);
    }
  }

  /*
   * Open plot device for plotting
   */


  if(plot_open(cheight))
    no_error = 0;

  /*
   * Plot contours
   */

  if(no_error) {
    ypos = (int) floor(minpos/nx) + 1;
    xpos = minpos - (ypos-1)*nx + 1;
    printf("\nminpos = %d, xpos = %d, ypos = %d\n\n",minpos,xpos,ypos);
    if(plot_contours(chisq,nx,ny,xpos,ypos,x[minpos],y[minpos],
		     chisq[minpos]) == 1)
      no_error = 0;
  }

  /*
   * Create chisq vs. lag cut at best value of flux ratio
   */

  if(no_error)
    if(onedslice(x,y,rchisq,nx,ny,minpos))
      no_error = 0;

  /*
   * Clean up
   */

  plot_close();
  x = del_array(x);
  y = del_array(y);
  chisq = del_array(chisq);
  rchisq = del_array(rchisq);

  if(no_error) {
    printf("\nFinished with program plot_chisq.c\n\n");
    return 0;
  }
  else {
    fprintf(stderr,"ERROR. Exiting program.\n");
    return 1;
  }
}

/*.......................................................................
 *
 * Function minmax
 *
 * Finds the minimum and maximum values in an array of floats and returns
 *  these values.  Also returns the array position of the min and max
 *  values.
 *
 * Inputs: float *array        array to be searched
 *         int size            size of array
 *         float *min          minimum value -- set by this function
 *         float *max          maximum value -- set by this function
 *         int *minpos         index of minimum value -- set by this function
 *         int *maxpos         index of maximum value -- set by this function
 *         char *arrname       name of array
 *         int verbose         verbose output if set to 1
 *
 * Output: int (0 or 1)        0 ==> success, 1 ==> error
 *
 */

int minmax(float *array, int size, float *min, float *max, int *minpos, 
	   int *maxpos, char *arrname, int verbose)
{
  int i;          /* Looping variable */
  float *arrptr;  /* Pointer for navigating array */

  /*
   * Initialize min and max values
   */

  *min = *array;
  *max = *array;
  *minpos = *maxpos = 0;

  /*
   * Loop through array searching for min and max values
   */

  for(i=0,arrptr=array; i<size; i++,arrptr++) {
    if(*arrptr > *max) {
      *max = *arrptr;
      *maxpos = i;
    }
    if(*arrptr < *min) {
      *min = *arrptr;
      *minpos = i;
    }
  }

  /*
   * Print out results
   */

  if(verbose)
    printf("For %s array, min = %f at index %d and max = %f at index %d\n\n",
	   arrname,*min,*minpos,*max,*maxpos);

  return 0;
}

/*.......................................................................
 *
 * Function plot_contours
 *
 * Plots the chisq contours.  To find the 68.3, 90, 95.4, and 99% confidence
 *  contours for ONE of the fitted variables, project the ellipses with
 *  Delta_chi^2 = 1.00, 2.71, 4.00, and 6.63 onto the relevant axis.
 *
 * Inputs: float *chisq        array of chisq values to be contoured
 *         int nx              size of x dimension of array
 *         int ny              size of y dimension of array
 *         float xmin,xmax     min and max values of x axis
 *         float ymin,ymax     min and max values of y axis
 *         float chimin        minimum value of chisq -- used to set contour
 *                              levels.
 *
 * Output: int (0 or 1)        0 ==> success, 1 ==> error
 *
 */

int plot_contours(float *chisq, int nx, int ny, float centx, float centy,
		  float centxval, float centyval, float chimin)
{
  int i;               /* Looping variable */
  int no_error=1;      /* Flag set to 0 on error */
  int ixstart,ixend;   /* Starting and ending positions in x */
  int iystart,iyend;   /* Starting and ending positions in y */
  float cheight=1.5;   /* Character height for axis labels */
  float *cont=NULL;    /* Array of contour levels */
  float tr[6] = {0,1,0,0,0,1};  /* Image -> world coord. transfer matrix */
  
  /*
   * Set the image window to be best-fit delay +/- 15 days and best-fit
   *  flux ratio +/- 1.5%.
   */

  if((ixstart = centx-3) < 1)
    ixstart = 1;
  if((iystart = centy-5) < 1)
    ixstart = 1;
  if((ixend = centx+3) > nx)
    ixend = nx;
  if((iyend = centy+5) > ny)
    ixend = ny;

  cpgsch(cheight);
  cpgswin(ixstart,ixend,iystart,iyend);

  /*
   * Set up the contour levels
   */

  if(!(cont = new_array(NCONT,1)))
    no_error = 0;

  if(no_error) {
    cont[0] = chimin + 1.00;
    cont[1] = chimin + 2.71;
    cont[2] = chimin + 4.00;
    cont[3] = chimin + 6.63;
  }

  /*
   * Put contours on the image
   */

  cpgsci(1);
  if(cont && no_error)
    cpgcont(chisq,nx,ny,ixstart,ixend,iystart,iyend,cont,4,tr);
  else {
    fprintf(stderr,"ERROR: plot_contours.  NULL contour array.\n");
    no_error = 0;
  }

  /*
   * Mark the best-fit value
   */

  cpgsch(3.0);
  cpgpt(1,&centx,&centy,3);

  /*
   * Label the boundaries
   */

  cpgswin(centxval-3,centxval+3,0.995*centyval,1.005*centyval);
  cpgscf(2);
  cpgslw(2);
  cpgsch(cheight);
  cpgbox("BCNST", 0, 0, "BCNST", 0, 0);
  cpglab("Lag (days)","Flux density ratio","");
  cpgsch(1.0);
  cpgslw(1);
  cpgscf(1);

  /*
   * Clean up
   */

  cont = del_array(cont);

  if(no_error)
    return 0;
  else {
    fprintf(stderr,"ERROR: plot_contours.\n");
    return 1;
  }

}

/*.......................................................................
 *
 * Function onedslice
 *
 * Creates a one-dimensional slice through the chisq surface passing through
 *  the minimum value of chisq to produce a graph of chisq vs. lag.
 *
 * Inputs: float *x            x array
 *         float *y            y array
 *         float *chisq        chisq array
 *         int nx,ny           dimensions of arrays
 *         int minpos          position in array of minimum chisq.
 *
 * Output: int (0 or 1)        0 ==> success, 1 ==> error
 *
 */

int onedslice(float *x, float *y, float *chisq, int nx, int ny, int minpos)
{
  int i;            /* Looping variable */
  int no_error=1;   /* Flag set to 0 on error */
  float ymin;       /* y value of min chisq point */
  float chimax=0.0; /* Maximum chisq value along curve */
  float *xptr;      /* Pointer for navigating x */
  float *yptr;      /* Pointer for navigating y */
  float *chiptr;    /* Pointer for navigating chisq */
  float *cxx=NULL;  /* Array of x points on best fit slice at constant y */
  float *cyx=NULL;  /* Array of y points on best fit slice at constant y */
  float *cxxptr;    /* Pointer for navigating cxx */
  float *cyxptr;    /* Pointer for navigating cyx */

  /*
   * Find the y value of the minimum-chisq point
   */

  ymin = y[minpos];

  /*
   * Allocate memory for cxx and cyx
   */

  if(!(cxx = new_array(nx,1))) {
    fprintf(stderr,"ERROR: onedslice.\n");
    return 1;
  }

  if(!(cyx = new_array(nx,1))) {
    no_error = 0;
  }

  /*
   * Put values into xslice
   */

  if(no_error) {
    cxxptr = cxx;
    cyxptr = cyx;
    for(i=0,xptr=x,yptr=y,chiptr=chisq; i<nx*ny; i++,xptr++,yptr++,chiptr++) {
      if(*yptr == ymin) {
	*cxxptr = *xptr;
	*cyxptr = *chiptr;
	cxxptr++;
	cyxptr++;
	if(*chiptr > chimax)
	  chimax = *chiptr;
      }
    }
  }

  /*
   * Plot curve
   */

  if(no_error)
    if(plot_curve(cxx,cyx,nx,chimax,"Lag (days)"))
      no_error = 0;

  /*
   * Clean up and exit
   */

  cxx = del_array(cxx);
  cyx = del_array(cyx);

  if(no_error)
    return 0;
  else {
    fprintf(stderr,"ERROR: onedslice.\n");
    return 1;
  }
}

/*.......................................................................
 *
 * Function plot_curve
 *
 * Plots a simple curve.
 *
 * Inputs: float *cx           x coordinates of curve
 *         float *cy           y coordinates of curve
 *         int size            size of Pos array
 *         float ymax          max value of y axis
 *         char *xlab          x label
 *
 * Output: int (0 or 1)        0 ==> success, 1 ==> error
 *
 */

int plot_curve(float *cx, float *cy, int size, float ymax, char *xlab)
{
  int no_error=1;      /* Flag set to 0 on error */
  float cheight=1.5;   /* Character height for axis labels */
  
  /*
   * Set the image window
   */

  cpgslw(4);
  cpgsch(cheight);
  cpgenv(-114.0,114.0,0.0,1.05*ymax,0,0);

  /*
   * Draw the curve
   */

  cpgline(size,cx,cy);

  /*
   * Label the boundaries
   */

  cpgscf(2);
  cpgslw(1);
  cpglab(xlab,"Reduced \\gx\\u2\\d","");
  cpgsch(1.0);

  /*
   * Clean up
   */

  if(no_error)
    return 0;
  else {
    fprintf(stderr,"ERROR: plot_curve.\n");
    return 1;
  }

}

/*.......................................................................
 *
 * Weird function to make pgplot work
 *
 */

int MAIN_(void)
{
  
  return 0;
}
