"""
Code to find a RA,Dec translation between an input fits file and an
astrometric catalog.  Optionally apply a correction to the WCS in the
fits file header to improve the match.

Usage: python ast_shift.py [fitsfile] [fitscat] [astcat]

Inputs:
   1. Input fits file with valid WCS information in the header
   2. Catalog file previously generated by running SExtractor on the input
      fits file (assumed to be in fits LDAC format)
   3. Astrometric catalog file (assumed to be in fits LDAC format)
   4. Maximum offset for a "good" match, in arcsec
"""

try:
   from astropy.io import fits as pf
except:
   import pyfits as pf
import matchcat as mc
import sys

""" Check the command line invocation """
if len(sys.argv)<4:
    print ''
    print 'Usage: python ast_shift.py [fitsfile] [fitscat] [astcat]'
    print ''
    print 'Inputs:'
    print '   1. Input fits file with valid WCS information in the header'
    print '   2. Catalog file previously generated by running SExtractor on the'
    print '       input fits file (assumed to be in fits LDAC format)'
    print '   3. Astrometric catalog file (assumed to be in fits LDAC format)'
    print '   4. Maximum offset for a good match, in arcsec'
    print ''
    exit()

""" Set variables """
fitsfile = sys.argv[1]
fitscat  = sys.argv[2]
astcat   = sys.argv[3]
rmax     = float(sys.argv[4])

""" Do the catalog matching """
fcat,acat = mc.find_match(fitscat,astcat,rmax,catformat1='ldac',
                          catformat2='ldac')


